package com.brandPitara.sfs.builderimprovement.enums;

public enum BuilderImprovementActionType {
    TIMELINE_OPTIMIZATION,
    CUSTOMER_SUPPORT_HUB,
    DOCUMENTATION_TRANSPARENCY,
    PROJECT_MONITORING,
    CONTRACTOR_CHANGED,
    SITE_MANPOWER_INCREASED,
    APPROVAL_CLEARED,
    MONTHLY_BUYER_UPDATES,
    PENDING_COMPLAINTS_REDUCED,
    SITE_PROGRESS_TRACKING,
    COMMUNITY_CONTRIBUTION,
    OTHER
}