package com.brandPitara.sfs.builderimprovement.enums;

public enum BuilderImprovementTimelineType {
    DELAY_OBSERVATION,
    AUDIT_INITIATED,
    TRANSPARENCY_PROTOCOL,
    MILESTONE_VERIFICATION,
    DELIVERY_CERTIFICATION,
    CUSTOMER_SUPPORT_UPDATE,
    DOCUMENTATION_UPDATE,
    ISSUE_RESOLUTION,

    CONSTRUCTION_PROGRESS,
    TOWER_COMPLETION,
    FLOOR_COMPLETION,
    AMENITY_PROGRESS,
    APPROVAL_PROGRESS,
    QUALITY_CHECK,
    HANDOVER_PROGRESS,
    POST_DELIVERY_SUPPORT,
    COMMUNITY_CONTRIBUTION,

    OTHER
}