package com.brandPitara.sfs.dashboard.common.enums;

public enum DashboardAuditAction {

    PROJECT_CREATED, PROJECT_UPDATED, PROJECT_DELETED, PROJECT_BUILDER_REASSIGNED,
    PROJECT_PUBLISHED, PROJECT_UNPUBLISHED,
    PROJECT_ACTIVATED, PROJECT_DEACTIVATED,
    PROJECT_SUBMITTED_FOR_REVIEW, PROJECT_APPROVED, PROJECT_APPROVAL_ROLLED_BACK, PROJECT_REJECTED, PROJECT_REOPENED,

    MEDIA_ADDED, MEDIA_UPDATED, MEDIA_DELETED,

    FLOOR_PLAN_CREATED, FLOOR_PLAN_UPDATED, FLOOR_PLAN_DELETED, FLOOR_PLAN_ACTIVATED,

    HIGHLIGHT_CREATED, HIGHLIGHT_UPDATED, HIGHLIGHT_DELETED,

    CONNECTIVITY_UPSERTED,
    CONNECTIVITY_PLACE_ADDED, CONNECTIVITY_PLACE_UPDATED, CONNECTIVITY_PLACE_DELETED,

    PROJECT_MASTER_PLAN_UPSERTED,
    PROJECT_MASTER_PLAN_ACTIVATED,
    PROJECT_MASTER_PLAN_DELETED,

    CONSTRUCTION_STAGE_CREATED, CONSTRUCTION_STAGE_UPDATED, CONSTRUCTION_STAGE_DELETED,
    COMPLIANCE_ITEM_CREATED, COMPLIANCE_ITEM_UPDATED, COMPLIANCE_ITEM_DELETED,
    AMENITY_CREATED, AMENITY_UPDATED, AMENITY_DELETED,
    PRICE_HISTORY_CREATED, PRICE_HISTORY_UPDATED, PRICE_HISTORY_DELETED,
    PAYMENT_MILESTONE_CREATED, PAYMENT_MILESTONE_UPDATED, PAYMENT_MILESTONE_DELETED,
    COST_BREAKDOWN_UPSERTED, LAND_UTILIZATION_UPSERTED, LOCATION_SCORE_UPSERTED,
    SNAPSHOT_RECALCULATED, SNAPSHOT_VERIFIED, SNAPSHOT_UNVERIFIED, PRICE_INSIGHTS_UPDATED,

    BUILDER_CREATED, BUILDER_UPDATED, BUILDER_DELETED, BUILDER_PUBLISHED, BUILDER_LOGO_UPDATED,

    BUILDER_IMPROVEMENT_PROFILE_UPSERTED,
    BUILDER_IMPROVEMENT_PROFILE_PUBLISHED,
    BUILDER_IMPROVEMENT_PROFILE_UNPUBLISHED,
    BUILDER_IMPROVEMENT_PROFILE_DELETED,

    BUILDER_IMPROVEMENT_ACTION_CREATED,
    BUILDER_IMPROVEMENT_ACTION_UPDATED,
    BUILDER_IMPROVEMENT_ACTION_DELETED,

    BUILDER_IMPROVEMENT_ISSUE_CREATED,
    BUILDER_IMPROVEMENT_ISSUE_UPDATED,
    BUILDER_IMPROVEMENT_ISSUE_DELETED,

    BUILDER_AFTER_SALES_UPGRADE_CREATED,
    BUILDER_AFTER_SALES_UPGRADE_UPDATED,
    BUILDER_AFTER_SALES_UPGRADE_DELETED,

    BUILDER_IMPROVEMENT_TIMELINE_CREATED,
    BUILDER_IMPROVEMENT_TIMELINE_UPDATED,
    BUILDER_IMPROVEMENT_TIMELINE_DELETED,

    BUILDER_HIGHLIGHT_CREATED,
    BUILDER_HIGHLIGHT_UPDATED,
    BUILDER_HIGHLIGHT_DELETED,
    BUILDER_HIGHLIGHT_STATUS_UPDATED,
    BUILDER_HIGHLIGHT_PUBLISHED,
    BUILDER_HIGHLIGHT_UNPUBLISHED,

    CITY_CREATED, CITY_UPDATED, CITY_DELETED,

    CATEGORY_CREATED, CATEGORY_UPDATED, CATEGORY_DELETED,

    COMPANY_PROJECT_BRAND_CREATED, COMPANY_PROJECT_BRAND_UPDATED, COMPANY_PROJECT_BRAND_DELETED
}
