package com.brandPitara.sfs.dashboard.common.enums;

public enum DashboardAuditAction {

    PROJECT_CREATED, PROJECT_UPDATED, PROJECT_DELETED,
    PROJECT_PUBLISHED, PROJECT_UNPUBLISHED,
    PROJECT_ACTIVATED, PROJECT_DEACTIVATED,
    PROJECT_SUBMITTED_FOR_REVIEW, PROJECT_APPROVED, PROJECT_REJECTED, PROJECT_REOPENED,

    MEDIA_ADDED, MEDIA_UPDATED, MEDIA_DELETED,

    FLOOR_PLAN_CREATED, FLOOR_PLAN_UPDATED, FLOOR_PLAN_DELETED, FLOOR_PLAN_ACTIVATED,

    HIGHLIGHT_CREATED, HIGHLIGHT_UPDATED, HIGHLIGHT_DELETED,

    CONNECTIVITY_UPSERTED,
    CONNECTIVITY_PLACE_ADDED, CONNECTIVITY_PLACE_UPDATED, CONNECTIVITY_PLACE_DELETED,

    CONSTRUCTION_STAGE_CREATED, CONSTRUCTION_STAGE_UPDATED, CONSTRUCTION_STAGE_DELETED,
    COMPLIANCE_ITEM_CREATED, COMPLIANCE_ITEM_UPDATED, COMPLIANCE_ITEM_DELETED,
    AMENITY_CREATED, AMENITY_UPDATED, AMENITY_DELETED,
    PRICE_HISTORY_CREATED, PRICE_HISTORY_UPDATED, PRICE_HISTORY_DELETED,
    PAYMENT_MILESTONE_CREATED, PAYMENT_MILESTONE_UPDATED, PAYMENT_MILESTONE_DELETED,
    COST_BREAKDOWN_UPSERTED, LAND_UTILIZATION_UPSERTED, LOCATION_SCORE_UPSERTED,
    SNAPSHOT_RECALCULATED,

    BUILDER_CREATED, BUILDER_UPDATED, BUILDER_DELETED, BUILDER_PUBLISHED,

    CITY_CREATED, CITY_UPDATED, CITY_DELETED,

    CATEGORY_CREATED, CATEGORY_UPDATED, CATEGORY_DELETED
}
