package com.brandPitara.sfs.dashboard.common.enums;

public enum DashboardHelpModule {
    PROJECT_BASIC,
    PROJECT_MEDIA,
    PROJECT_FLOOR_PLAN,
    PROJECT_HIGHLIGHT,
    PROJECT_CONNECTIVITY,
    PROJECT_METER_CONSTRUCTION_STAGE,
    PROJECT_METER_COMPLIANCE,
    PROJECT_METER_AMENITY,
    PROJECT_METER_PRICE_HISTORY,
    PROJECT_METER_PAYMENT_MILESTONE,
    PROJECT_METER_COST_BREAKDOWN,
    PROJECT_METER_LAND_UTILIZATION,
    PROJECT_METER_LOCATION_SCORE,
    BUILDER
}
