package com.brandPitara.sfs.dashboard.common.enums;

public enum DashboardHelpModule {
    PROJECT_BASIC,
    PROJECT_MEDIA,
    PROJECT_FLOOR_PLAN,
    PROJECT_HIGHLIGHT,
    PROJECT_CONNECTIVITY,
    PROJECT_MASTER_PLAN,
    PROJECT_METER_CONSTRUCTION_STAGE,
    PROJECT_METER_COMPLIANCE,
    PROJECT_METER_AMENITY,
    PROJECT_METER_PRICE_HISTORY,
    PROJECT_METER_PAYMENT_MILESTONE,
    PROJECT_METER_COST_BREAKDOWN,
    PROJECT_METER_LAND_UTILIZATION,
    PROJECT_METER_LOCATION_SCORE,

    BUILDER,

    BUILDER_IMPROVEMENT_PROFILE,
    BUILDER_IMPROVEMENT_ACTION,
    BUILDER_IMPROVEMENT_ISSUE,
    BUILDER_AFTER_SALES_UPGRADE,
    BUILDER_IMPROVEMENT_TIMELINE
}
