package com.brandPitara.sfs.migration;

import org.flywaydb.core.api.Location;
import org.flywaydb.core.internal.resolver.ChecksumCalculator;
import org.flywaydb.core.internal.resource.filesystem.FileSystemResource;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;

class FlywayRepairStructureTest {

    /**
     * Checksums as they exist in a real flyway_schema_history for an
     * environment these migrations were already applied to (Flyway's own CRC32
     * algorithm, verified via org.flywaydb.core.internal.resolver.ChecksumCalculator
     * - not a generic SHA-256 of the file, which is a different, unrelated
     * value). Extend this map, never edit an existing entry: an existing entry
     * changing to match a locally-modified file would silently defeat this
     * test's whole purpose.
     */
    private static final Map<String, Integer> KNOWN_APPLIED_MIGRATION_CHECKSUMS = new LinkedHashMap<>();

    static {
        KNOWN_APPLIED_MIGRATION_CHECKSUMS.put("V135__add_promo_banner_video_crud_support.sql", 572705898);
        KNOWN_APPLIED_MIGRATION_CHECKSUMS.put("V136__extend_company_project_cms.sql", 497289893);
        KNOWN_APPLIED_MIGRATION_CHECKSUMS.put("V137__add_instagram_reel_preview_image_url.sql", 1594241930);
        KNOWN_APPLIED_MIGRATION_CHECKSUMS.put("V138__floor_plan_room_comparison_and_visual_analysis.sql", -325133805);
        KNOWN_APPLIED_MIGRATION_CHECKSUMS.put("V139__add_floor_plan_insight_dimension_text.sql", -1654764690);
        KNOWN_APPLIED_MIGRATION_CHECKSUMS.put("V140__repair_historical_schema_drift.sql", 1419121350);
        KNOWN_APPLIED_MIGRATION_CHECKSUMS.put("V141__restore_canonical_baseline_reference_data.sql", 1461039657);
        KNOWN_APPLIED_MIGRATION_CHECKSUMS.put("V142__add_company_project_slug_unique_index.sql", -511850496);
    }

    // Group 1 is the prefix (V = versioned migration, B = baseline marker - Flyway
    // treats these as separate namespaces, so "B134" and "V134" coexisting is not
    // a collision); group 2 is the version number.
    private static final Pattern VERSIONED_MIGRATION_FILENAME = Pattern.compile("^([VB])(\\d+(?:_\\d+)*)__.*\\.sql$");

    @Test
    void baselineAndForwardRepairExistWithoutSchemaRepairCallback() {
        assertThat(new ClassPathResource(
                "db/migration/B134__sfs_schema_baseline.sql"
        ).exists()).isTrue();

        KNOWN_APPLIED_MIGRATION_CHECKSUMS.keySet().forEach(fileName ->
                assertThat(new ClassPathResource(
                        "db/migration/" + fileName
                ).exists())
                        .as("known-applied migration %s must exist", fileName)
                        .isTrue()
        );

        assertThat(new ClassPathResource(
                "db/local-staging/beforeEachMigrate.sql"
        ).exists()).isFalse();
    }

    /**
     * General invariant: any migration already applied somewhere must never be
     * edited afterward - Flyway itself enforces this at startup via checksum
     * validation and refuses to boot on a mismatch. This test catches the same
     * class of problem earlier, in code review, using Flyway's own checksum
     * algorithm (not a stand-in like SHA-256) so the computed value is exactly
     * what flyway_schema_history.checksum would show. Add new entries to
     * KNOWN_APPLIED_MIGRATION_CHECKSUMS as more migrations are confirmed
     * applied to any real environment - this loop needs no other change to
     * cover them.
     */
    @Test
    void knownAppliedMigrationsRemainByteForByteImmutable() throws Exception {
        Path migrationsDir = new ClassPathResource("db/migration").getFile().toPath();

        for (Map.Entry<String, Integer> expected : KNOWN_APPLIED_MIGRATION_CHECKSUMS.entrySet()) {
            String fileName = expected.getKey();
            Path file = migrationsDir.resolve(fileName);

            assertThat(Files.exists(file))
                    .as("known-applied migration %s must exist", fileName)
                    .isTrue();

            int actualChecksum = flywayChecksum(migrationsDir, file);

            assertThat(actualChecksum)
                    .as("known-applied migration %s must keep the exact checksum it was applied with "
                            + "(Flyway will refuse to start against any environment that already ran the "
                            + "original content otherwise) - do not edit this file; add a new migration instead",
                            fileName)
                    .isEqualTo(expected.getValue());
        }
    }

    /**
     * General invariant, not incident-specific: no two migration files may
     * declare the same version number, regardless of filename. A previous
     * incident renumbered already-applied migrations under new filenames
     * (V135-139 duplicated as V143-146 with identical content) - rather than
     * hardcode those four filenames, this parses every V<n>__/B<n>__ file in
     * the directory and asserts version uniqueness directly, so it also
     * catches any future renumbering under still other names.
     */
    @Test
    void noTwoMigrationFilesShareTheSameVersionNumber() throws Exception {
        Path migrationsDir = new ClassPathResource("db/migration").getFile().toPath();

        Map<String, List<String>> filenamesByVersion = new HashMap<>();
        try (var files = Files.list(migrationsDir)) {
            for (Path path : files.collect(Collectors.toList())) {
                String fileName = path.getFileName().toString();
                Matcher matcher = VERSIONED_MIGRATION_FILENAME.matcher(fileName);
                if (matcher.matches()) {
                    String namespacedVersion = matcher.group(1) + matcher.group(2);
                    filenamesByVersion
                            .computeIfAbsent(namespacedVersion, ignored -> new java.util.ArrayList<>())
                            .add(fileName);
                }
            }
        }

        Map<String, List<String>> duplicateVersions = filenamesByVersion.entrySet().stream()
                .filter(entry -> entry.getValue().size() > 1)
                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));

        assertThat(duplicateVersions)
                .as("each migration version number must map to exactly one file; duplicates found: %s",
                        duplicateVersions)
                .isEmpty();
    }

    @Test
    void migrationSequenceContainsCanonicalProductionHistory() throws Exception {
        Path migrations = new ClassPathResource("db/migration").getFile().toPath();

        Set<String> migrationNames;
        try (var files = Files.list(migrations)) {
            migrationNames = files
                    .map(path -> path.getFileName().toString())
                    .collect(Collectors.toSet());
        }

        assertThat(migrationNames).containsAll(KNOWN_APPLIED_MIGRATION_CHECKSUMS.keySet());
    }

    @Test
    void localStagingLoadsOnlyNormalMigrationLocation() throws Exception {
        Path config =
                new ClassPathResource("application-local-staging.yml")
                        .getFile()
                        .toPath();

        String yaml = Files.readString(config, StandardCharsets.UTF_8);

        assertThat(yaml)
                .contains("locations: classpath:db/migration")
                .doesNotContain("classpath:db/local-staging")
                .contains("ddl-auto: validate")
                .contains("open-in-view: false");
    }

    @Test
    void localStagingSmokeChecksActualDockerPortBindings() throws Exception {
        Path smoke = Path.of("infra/local-staging/smoke.sh");
        String script = Files.readString(smoke, StandardCharsets.UTF_8);

        assertThat(script)
                .contains(".HostConfig.PortBindings")
                .doesNotContain("compose port backend")
                .doesNotContain("compose port postgres");
    }

    /** Flyway's real checksum algorithm (CRC32 per line, combined) - not a generic file hash. */
    private static int flywayChecksum(Path migrationsDir, Path file) {
        Location location = new Location(Location.FILESYSTEM_PREFIX + migrationsDir);
        FileSystemResource resource =
                new FileSystemResource(location, file.toString(), StandardCharsets.UTF_8, false);
        return ChecksumCalculator.calculate(resource);
    }
}
