package com.brandPitara.sfs.dashboard.company.service.impl;

import com.brandPitara.sfs.brand.repository.BrandCollaborationRepository;
import com.brandPitara.sfs.company.entity.CompanyEntity;
import com.brandPitara.sfs.company.repository.CompanyRepository;
import com.brandPitara.sfs.dashboard.company.dto.CompanyCreateRequest;
import com.brandPitara.sfs.dashboard.company.dto.CompanyDetailResponse;
import com.brandPitara.sfs.dashboard.company.dto.CompanyListItemResponse;
import com.brandPitara.sfs.dashboard.company.dto.CompanyUpdateRequest;
import com.brandPitara.sfs.entity.CityEntity;
import com.brandPitara.sfs.repository.CityRepository;
import jakarta.persistence.EntityNotFoundException;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.web.server.ResponseStatusException;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class DashboardCompanyServiceImplTest {

  @Mock private CompanyRepository companyRepository;
  @Mock private CityRepository cityRepository;
  @Mock private BrandCollaborationRepository brandCollaborationRepository;

  private static final ValidatorFactory VALIDATOR_FACTORY = Validation.buildDefaultValidatorFactory();
  private static final Validator VALIDATOR = VALIDATOR_FACTORY.getValidator();

  private DashboardCompanyServiceImpl service() {
    return new DashboardCompanyServiceImpl(companyRepository, cityRepository, brandCollaborationRepository);
  }

  private CityEntity city() {
    return CityEntity.builder().id(9L).name("Gurgaon").build();
  }

  private CompanyEntity company(Long id) {
    return CompanyEntity.builder()
        .id(id)
        .name("Morphogenesis")
        .slug("morphogenesis")
        .companyType("ARCHITECT&DESIGNERS")
        .city(city())
        .active(true)
        .published(true)
        .priority(0)
        .deleted(false)
        .build();
  }

  @Test
  void list_returnsNonDeletedCompaniesWithCityAndConnectedBrandsCount() {
    CompanyEntity company = company(1L);
    Page<CompanyEntity> page = new PageImpl<>(List.of(company));
    when(companyRepository.searchForDashboard(isNull(), isNull(), isNull(), isNull(), any(Pageable.class)))
        .thenReturn(page);
    when(brandCollaborationRepository.countConnectedBrandsByCompanyIds(List.of(1L)))
        .thenReturn(List.<Object[]>of(new Object[]{1L, 2L}));

    Page<CompanyListItemResponse> result = service().list(null, null, null, null, null, Pageable.unpaged());

    assertThat(result.getContent()).hasSize(1);
    CompanyListItemResponse item = result.getContent().get(0);
    assertThat(item.getId()).isEqualTo(1L);
    assertThat(item.getCityName()).isEqualTo("Gurgaon");
    assertThat(item.getConnectedBrandsCount()).isEqualTo(2L);
  }

  @Test
  void list_usesNameSearchQueryOnlyWhenQHasText() {
    Page<CompanyEntity> page = new PageImpl<>(List.of());
    when(companyRepository.searchForDashboardByName(
        eq("morpho"), isNull(), isNull(), isNull(), isNull(), any(Pageable.class)))
        .thenReturn(page);

    service().list("morpho", null, null, null, null, Pageable.unpaged());

    verify(companyRepository).searchForDashboardByName(
        eq("morpho"), isNull(), isNull(), isNull(), isNull(), any(Pageable.class));
    verify(companyRepository, never()).searchForDashboard(any(), any(), any(), any(), any());
  }

  @Test
  void create_succeedsWithAutoGeneratedSlug() {
    when(companyRepository.findBySlug("morphogenesis")).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .build();

    CompanyDetailResponse response = service().create(request);

    assertThat(response.getName()).isEqualTo("Morphogenesis");
    assertThat(response.getSlug()).isEqualTo("morphogenesis");
    assertThat(response.getCompanyType()).isEqualTo("ARCHITECT");
    assertThat(response.isPublished()).isFalse();
    assertThat(response.isActive()).isTrue();
  }

  @Test
  void create_rejectsMissingCityWhenCityIdInvalid() {
    when(cityRepository.findById(999L)).thenReturn(Optional.empty());

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .cityId(999L)
        .build();

    assertThatThrownBy(() -> service().create(request)).isInstanceOf(EntityNotFoundException.class);
    verify(companyRepository, never()).save(any());
  }

  @Test
  void create_persistsServicesOfferedAsCommaJoinedText() {
    when(companyRepository.findBySlug(anyString())).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .servicesOffered(List.of("Interior Design", "Architecture"))
        .build();

    CompanyDetailResponse response = service().create(request);

    assertThat(response.getServicesOffered()).containsExactly("Interior Design", "Architecture");
  }

  @Test
  void create_persistsMultiWordServicesWithoutConcatenation() {
    // Regression guard for the dashboard bug where "House Interior, Modular Kitchen,
    // Bedroom Design, Living Spaces" rendered/saved as one concatenated blob
    // ("HouseInteriorModularKitchenBedroomDesignLivingSpaces"). The backend join/split
    // (joinServices/CompanyProjectTagMapper.toTags) already preserves spaces and
    // separators correctly - this test proves that end to end at the service layer.
    when(companyRepository.findBySlug(anyString())).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .servicesOffered(List.of("House Interior", "Modular Kitchen", "Bedroom Design", "Living Spaces"))
        .build();

    CompanyDetailResponse response = service().create(request);

    assertThat(response.getServicesOffered())
        .containsExactly("House Interior", "Modular Kitchen", "Bedroom Design", "Living Spaces");
  }

  @Test
  void servicesOffered_rejectsMoreThan20Entries_viaBeanValidation() {
    List<String> tooMany = new ArrayList<>();
    for (int i = 0; i < 21; i++) tooMany.add("Service " + i);

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .servicesOffered(tooMany)
        .build();

    Set<ConstraintViolation<CompanyCreateRequest>> violations = VALIDATOR.validate(request);

    assertThat(violations)
        .extracting(v -> v.getPropertyPath().toString())
        .contains("servicesOffered");
  }

  @Test
  void servicesOffered_rejectsEntryLongerThan60Chars_viaBeanValidation() {
    String tooLong = "x".repeat(61);

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .servicesOffered(List.of(tooLong))
        .build();

    Set<ConstraintViolation<CompanyCreateRequest>> violations = VALIDATOR.validate(request);

    assertThat(violations).isNotEmpty();
  }

  @Test
  void update_succeeds() {
    CompanyEntity existing = company(1L);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(existing));
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyUpdateRequest request = CompanyUpdateRequest.builder()
        .description("Updated description")
        .active(false)
        .build();

    CompanyDetailResponse response = service().update(1L, request);

    assertThat(response.getDescription()).isEqualTo("Updated description");
    assertThat(response.isActive()).isFalse();
  }

  @Test
  void update_rejectsDuplicateSlug() {
    CompanyEntity existing = company(1L);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(existing));
    when(companyRepository.findBySlugAndIdNot("taken-slug", 1L))
        .thenReturn(Optional.of(company(2L)));

    CompanyUpdateRequest request = CompanyUpdateRequest.builder().slug("taken-slug").build();

    assertThatThrownBy(() -> service().update(1L, request))
        .isInstanceOf(ResponseStatusException.class)
        .hasMessageContaining("already exists");
    verify(companyRepository, never()).save(any());
  }

  @Test
  void getDetail_throwsNotFound_forMissingOrDeletedCompany() {
    when(companyRepository.findByIdAndDeletedFalse(999L)).thenReturn(Optional.empty());

    assertThatThrownBy(() -> service().getDetail(999L)).isInstanceOf(EntityNotFoundException.class);
  }

  @Test
  void softDelete_setsDeletedActiveFalsePublishedFalse() {
    CompanyEntity existing = company(1L);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(existing));

    service().softDelete(1L);

    ArgumentCaptor<CompanyEntity> captor = ArgumentCaptor.forClass(CompanyEntity.class);
    verify(companyRepository).save(captor.capture());
    CompanyEntity saved = captor.getValue();
    assertThat(saved.getDeleted()).isTrue();
    assertThat(saved.getActive()).isFalse();
    assertThat(saved.getPublished()).isFalse();
  }
}
