package com.brandPitara.sfs.dashboard.company.service.impl;

import com.brandPitara.sfs.brand.repository.BrandCollaborationRepository;
import com.brandPitara.sfs.company.entity.CompanyEntity;
import com.brandPitara.sfs.company.repository.CompanyRepository;
import com.brandPitara.sfs.dashboard.company.dto.CompanyCreateRequest;
import com.brandPitara.sfs.dashboard.company.dto.CompanyDetailResponse;
import com.brandPitara.sfs.dashboard.company.dto.CompanyListItemResponse;
import com.brandPitara.sfs.dashboard.company.dto.CompanyUpdateRequest;
import com.brandPitara.sfs.entity.CityEntity;
import com.brandPitara.sfs.repository.CityRepository;
import jakarta.persistence.EntityNotFoundException;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.web.server.ResponseStatusException;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class DashboardCompanyServiceImplTest {

  @Mock private CompanyRepository companyRepository;
  @Mock private CityRepository cityRepository;
  @Mock private BrandCollaborationRepository brandCollaborationRepository;

  private static final ValidatorFactory VALIDATOR_FACTORY = Validation.buildDefaultValidatorFactory();
  private static final Validator VALIDATOR = VALIDATOR_FACTORY.getValidator();

  private DashboardCompanyServiceImpl service() {
    return new DashboardCompanyServiceImpl(companyRepository, cityRepository, brandCollaborationRepository);
  }

  private CityEntity city() {
    return CityEntity.builder().id(9L).name("Gurgaon").build();
  }

  private CompanyEntity company(Long id) {
    return CompanyEntity.builder()
        .id(id)
        .name("Morphogenesis")
        .slug("morphogenesis")
        .companyType("ARCHITECT&DESIGNERS")
        .city(city())
        .active(true)
        .published(true)
        .priority(0)
        .deleted(false)
        .build();
  }

  @Test
  void list_returnsNonDeletedCompaniesWithCityAndConnectedBrandsCount() {
    CompanyEntity company = company(1L);
    Page<CompanyEntity> page = new PageImpl<>(List.of(company));
    when(companyRepository.searchForDashboard(isNull(), isNull(), isNull(), isNull(), any(Pageable.class)))
        .thenReturn(page);
    when(brandCollaborationRepository.countConnectedBrandsByCompanyIds(List.of(1L)))
        .thenReturn(List.<Object[]>of(new Object[]{1L, 2L}));

    Page<CompanyListItemResponse> result = service().list(null, null, null, null, null, Pageable.unpaged());

    assertThat(result.getContent()).hasSize(1);
    CompanyListItemResponse item = result.getContent().get(0);
    assertThat(item.getId()).isEqualTo(1L);
    assertThat(item.getCityName()).isEqualTo("Gurgaon");
    assertThat(item.getConnectedBrandsCount()).isEqualTo(2L);
  }

  @Test
  void list_usesNameSearchQueryOnlyWhenQHasText() {
    Page<CompanyEntity> page = new PageImpl<>(List.of());
    when(companyRepository.searchForDashboardByName(
        eq("morpho"), isNull(), isNull(), isNull(), isNull(), any(Pageable.class)))
        .thenReturn(page);

    service().list("morpho", null, null, null, null, Pageable.unpaged());

    verify(companyRepository).searchForDashboardByName(
        eq("morpho"), isNull(), isNull(), isNull(), isNull(), any(Pageable.class));
    verify(companyRepository, never()).searchForDashboard(any(), any(), any(), any(), any());
  }

  @Test
  void create_succeedsWithAutoGeneratedSlug() {
    when(companyRepository.findBySlug("morphogenesis")).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .build();

    CompanyDetailResponse response = service().create(request);

    assertThat(response.getName()).isEqualTo("Morphogenesis");
    assertThat(response.getSlug()).isEqualTo("morphogenesis");
    assertThat(response.getCompanyType()).isEqualTo("ARCHITECT");
    assertThat(response.isPublished()).isFalse();
    assertThat(response.isActive()).isTrue();
  }

  @Test
  void create_rejectsMissingCityWhenCityIdInvalid() {
    when(cityRepository.findById(999L)).thenReturn(Optional.empty());

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .cityId(999L)
        .build();

    assertThatThrownBy(() -> service().create(request)).isInstanceOf(EntityNotFoundException.class);
    verify(companyRepository, never()).save(any());
  }

  @Test
  void create_persistsServicesOfferedAsCommaJoinedText() {
    when(companyRepository.findBySlug(anyString())).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .servicesOffered(List.of("Interior Design", "Architecture"))
        .build();

    CompanyDetailResponse response = service().create(request);

    assertThat(response.getServicesOffered()).containsExactly("Interior Design", "Architecture");
  }

  @Test
  void create_persistsMultiWordServicesWithoutConcatenation() {
    // Regression guard for the dashboard bug where "House Interior, Modular Kitchen,
    // Bedroom Design, Living Spaces" rendered/saved as one concatenated blob
    // ("HouseInteriorModularKitchenBedroomDesignLivingSpaces"). The backend join/split
    // (joinServices/CompanyProjectTagMapper.toTags) already preserves spaces and
    // separators correctly - this test proves that end to end at the service layer.
    when(companyRepository.findBySlug(anyString())).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .servicesOffered(List.of("House Interior", "Modular Kitchen", "Bedroom Design", "Living Spaces"))
        .build();

    CompanyDetailResponse response = service().create(request);

    assertThat(response.getServicesOffered())
        .containsExactly("House Interior", "Modular Kitchen", "Bedroom Design", "Living Spaces");
  }

  @Test
  void servicesOffered_rejectsMoreThan20Entries_viaBeanValidation() {
    List<String> tooMany = new ArrayList<>();
    for (int i = 0; i < 21; i++) tooMany.add("Service " + i);

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .servicesOffered(tooMany)
        .build();

    Set<ConstraintViolation<CompanyCreateRequest>> violations = VALIDATOR.validate(request);

    assertThat(violations)
        .extracting(v -> v.getPropertyPath().toString())
        .contains("servicesOffered");
  }

  @Test
  void servicesOffered_rejectsEntryLongerThan60Chars_viaBeanValidation() {
    String tooLong = "x".repeat(61);

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis")
        .companyType("ARCHITECT")
        .servicesOffered(List.of(tooLong))
        .build();

    Set<ConstraintViolation<CompanyCreateRequest>> violations = VALIDATOR.validate(request);

    assertThat(violations).isNotEmpty();
  }

  @Test
  void update_succeeds() {
    CompanyEntity existing = company(1L);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(existing));
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyUpdateRequest request = CompanyUpdateRequest.builder()
        .description("Updated description")
        .active(false)
        .build();

    CompanyDetailResponse response = service().update(1L, request);

    assertThat(response.getDescription()).isEqualTo("Updated description");
    assertThat(response.isActive()).isFalse();
  }

  @Test
  void update_rejectsDuplicateSlug() {
    CompanyEntity existing = company(1L);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(existing));
    when(companyRepository.findBySlugAndIdNot("taken-slug", 1L))
        .thenReturn(Optional.of(company(2L)));

    CompanyUpdateRequest request = CompanyUpdateRequest.builder().slug("taken-slug").build();

    assertThatThrownBy(() -> service().update(1L, request))
        .isInstanceOf(ResponseStatusException.class)
        .hasMessageContaining("already exists");
    verify(companyRepository, never()).save(any());
  }

  // ---------- Phase 7B-G: canonical slug format validation ----------

  @Test
  void create_withCanonicalCustomSlug_isAccepted() {
    when(companyRepository.findBySlug("my-custom-slug")).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis").companyType("ARCHITECT").slug("my-custom-slug").build();

    CompanyDetailResponse response = service().create(request);

    assertThat(response.getSlug()).isEqualTo("my-custom-slug");
  }

  @Test
  void create_withNonCanonicalCustomSlug_isRejectedWith400() {
    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis").companyType("ARCHITECT").slug("Not A Slug!!").build();

    assertThatThrownBy(() -> service().create(request))
        .isInstanceOf(ResponseStatusException.class)
        .hasMessageContaining("kebab-case");
    verify(companyRepository, never()).save(any());
  }

  @Test
  void create_withUppercaseCustomSlug_isRejected() {
    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis").companyType("ARCHITECT").slug("Morphogenesis-INC").build();

    assertThatThrownBy(() -> service().create(request)).isInstanceOf(ResponseStatusException.class);
  }

  @Test
  void create_withCustomSlugContainingLeadingHyphen_isRejected() {
    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis").companyType("ARCHITECT").slug("-morphogenesis").build();

    assertThatThrownBy(() -> service().create(request)).isInstanceOf(ResponseStatusException.class);
  }

  @Test
  void create_withCustomSlugContainingDoubleHyphen_isRejected() {
    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis").companyType("ARCHITECT").slug("morpho--genesis").build();

    assertThatThrownBy(() -> service().create(request)).isInstanceOf(ResponseStatusException.class);
  }

  @Test
  void update_withNonCanonicalCustomSlug_isRejectedOnADraftCompany() {
    CompanyEntity draft = company(1L);
    draft.setEverPublished(false);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(draft));

    CompanyUpdateRequest request = CompanyUpdateRequest.builder().slug("Not Canonical").build();

    assertThatThrownBy(() -> service().update(1L, request))
        .isInstanceOf(ResponseStatusException.class)
        .hasMessageContaining("kebab-case");
    verify(companyRepository, never()).save(any());
  }

  // ---------- Phase 7B-G: published-slug immutability (RISK-025) ----------

  @Test
  void create_publishedImmediately_marksEverPublishedTrue() {
    when(companyRepository.findBySlug(anyString())).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis").companyType("ARCHITECT").published(true).build();

    ArgumentCaptor<CompanyEntity> captor = ArgumentCaptor.forClass(CompanyEntity.class);
    service().create(request);
    verify(companyRepository).save(captor.capture());

    assertThat(captor.getValue().getPublished()).isTrue();
    assertThat(captor.getValue().getEverPublished()).isTrue();
  }

  @Test
  void create_asDraft_leavesEverPublishedFalse() {
    when(companyRepository.findBySlug(anyString())).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyCreateRequest request = CompanyCreateRequest.builder()
        .name("Morphogenesis").companyType("ARCHITECT").build();

    ArgumentCaptor<CompanyEntity> captor = ArgumentCaptor.forClass(CompanyEntity.class);
    service().create(request);
    verify(companyRepository).save(captor.capture());

    assertThat(captor.getValue().getPublished()).isFalse();
    assertThat(captor.getValue().getEverPublished()).isFalse();
  }

  @Test
  void update_allowsSlugChangeOnADraftCompanyThatHasNeverBeenPublished() {
    CompanyEntity draft = company(1L);
    draft.setPublished(false);
    draft.setEverPublished(false);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(draft));
    when(companyRepository.findBySlugAndIdNot("new-draft-slug", 1L)).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyUpdateRequest request = CompanyUpdateRequest.builder().slug("new-draft-slug").build();

    CompanyDetailResponse response = service().update(1L, request);

    assertThat(response.getSlug()).isEqualTo("new-draft-slug");
  }

  @Test
  void update_rejectsSlugChangeOnACompanyThatHasEverBeenPublished_evenIfCurrentlyUnpublished() {
    // The "unpublish -> edit -> republish" bypass this test protects against: everPublished
    // stays true even after the company is unpublished, so the slug edit below must still be
    // rejected - not because it's currently published (it isn't), but because it once was.
    CompanyEntity previouslyPublished = company(1L);
    previouslyPublished.setPublished(false);
    previouslyPublished.setEverPublished(true);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(previouslyPublished));

    CompanyUpdateRequest request = CompanyUpdateRequest.builder().slug("sneaky-new-slug").build();

    assertThatThrownBy(() -> service().update(1L, request))
        .isInstanceOf(ResponseStatusException.class)
        .hasMessageContaining("published");
    verify(companyRepository, never()).save(any());
  }

  @Test
  void update_rejectsSlugChangeOnACurrentlyPublishedCompany() {
    CompanyEntity published = company(1L);
    published.setPublished(true);
    published.setEverPublished(true);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(published));

    CompanyUpdateRequest request = CompanyUpdateRequest.builder().slug("another-new-slug").build();

    assertThatThrownBy(() -> service().update(1L, request)).isInstanceOf(ResponseStatusException.class);
    verify(companyRepository, never()).save(any());
  }

  @Test
  void update_firstPublicationInTheSameRequestThatSetsACustomSlug_allowsBoth() {
    // "Before first publication, a validated slug may be changed" explicitly includes the
    // moment of first publication itself - a single request may set the final slug and
    // publish=true together.
    CompanyEntity draft = company(1L);
    draft.setPublished(false);
    draft.setEverPublished(false);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(draft));
    when(companyRepository.findBySlugAndIdNot("final-slug", 1L)).thenReturn(Optional.empty());
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyUpdateRequest request = CompanyUpdateRequest.builder().slug("final-slug").published(true).build();

    CompanyDetailResponse response = service().update(1L, request);

    assertThat(response.getSlug()).isEqualTo("final-slug");
    assertThat(response.isPublished()).isTrue();
  }

  @Test
  void update_publishingForTheFirstTime_marksEverPublishedTrue() {
    CompanyEntity draft = company(1L);
    draft.setPublished(false);
    draft.setEverPublished(false);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(draft));
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    ArgumentCaptor<CompanyEntity> captor = ArgumentCaptor.forClass(CompanyEntity.class);
    service().update(1L, CompanyUpdateRequest.builder().published(true).build());
    verify(companyRepository).save(captor.capture());

    assertThat(captor.getValue().getEverPublished()).isTrue();
  }

  @Test
  void update_unpublishingAnAlreadyPublishedCompany_doesNotResetEverPublished() {
    CompanyEntity published = company(1L);
    published.setPublished(true);
    published.setEverPublished(true);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(published));
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    ArgumentCaptor<CompanyEntity> captor = ArgumentCaptor.forClass(CompanyEntity.class);
    service().update(1L, CompanyUpdateRequest.builder().published(false).build());
    verify(companyRepository).save(captor.capture());

    assertThat(captor.getValue().getPublished()).isFalse();
    assertThat(captor.getValue().getEverPublished()).isTrue();
  }

  @Test
  void update_nameChangeAloneNeverTouchesTheSlug() {
    CompanyEntity published = company(1L);
    published.setPublished(true);
    published.setEverPublished(true);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(published));
    when(companyRepository.save(any(CompanyEntity.class))).thenAnswer(inv -> inv.getArgument(0));

    CompanyDetailResponse response = service().update(1L,
        CompanyUpdateRequest.builder().name("Morphogenesis Studio Renamed").build());

    assertThat(response.getSlug()).isEqualTo("morphogenesis");
    assertThat(response.getName()).isEqualTo("Morphogenesis Studio Renamed");
  }

  @Test
  void softDelete_preservesTheExistingSlug() {
    CompanyEntity existing = company(1L);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(existing));

    service().softDelete(1L);

    ArgumentCaptor<CompanyEntity> captor = ArgumentCaptor.forClass(CompanyEntity.class);
    verify(companyRepository).save(captor.capture());
    assertThat(captor.getValue().getSlug()).isEqualTo("morphogenesis");
  }

  @Test
  void softDelete_neverTouchesEverPublished() {
    CompanyEntity existing = company(1L);
    existing.setEverPublished(true);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(existing));

    service().softDelete(1L);

    ArgumentCaptor<CompanyEntity> captor = ArgumentCaptor.forClass(CompanyEntity.class);
    verify(companyRepository).save(captor.capture());
    assertThat(captor.getValue().getEverPublished()).isTrue();
  }

  @Test
  void attemptingASlugEditAfterSoftDelete_isRejectedAsNotFound_notAsAnImmutabilityConflict() {
    // update() looks the company up via findByIdAndDeletedFalse - a soft-deleted company is
    // therefore already unreachable for ANY update, slug edits included, via a 404
    // (EntityNotFoundException), before the ever_published immutability check ever runs.
    // This codebase has no "restore" operation for Company at all (confirmed: no such method
    // exists on DashboardCompanyService) - so "delete/restore then attempted slug edit" from
    // Phase 7B-GA's own required test list reduces to exactly this: delete alone already
    // blocks every future slug edit attempt permanently, via 404, not via the 409 immutability
    // path (both are safe outcomes - the slug can never be changed either way - but they are
    // different exception types, and asserting the wrong one would be a false confirmation).
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.empty());

    CompanyUpdateRequest request = CompanyUpdateRequest.builder().slug("sneaky-post-delete-slug").build();

    assertThatThrownBy(() -> service().update(1L, request)).isInstanceOf(EntityNotFoundException.class);
    verify(companyRepository, never()).save(any());
  }

  @Test
  void getDetail_throwsNotFound_forMissingOrDeletedCompany() {
    when(companyRepository.findByIdAndDeletedFalse(999L)).thenReturn(Optional.empty());

    assertThatThrownBy(() -> service().getDetail(999L)).isInstanceOf(EntityNotFoundException.class);
  }

  @Test
  void softDelete_setsDeletedActiveFalsePublishedFalse() {
    CompanyEntity existing = company(1L);
    when(companyRepository.findByIdAndDeletedFalse(1L)).thenReturn(Optional.of(existing));

    service().softDelete(1L);

    ArgumentCaptor<CompanyEntity> captor = ArgumentCaptor.forClass(CompanyEntity.class);
    verify(companyRepository).save(captor.capture());
    CompanyEntity saved = captor.getValue();
    assertThat(saved.getDeleted()).isTrue();
    assertThat(saved.getActive()).isFalse();
    assertThat(saved.getPublished()).isFalse();
  }
}
